### ISSUE TITLE
Cannot save module

### ISSUE THREAD

**Issue by staffiery** [bramwaas/joomla_mod_simple_ical_block#10]
Just downloaded joomla_mod_simple_ical_block-2.1.1.zip and installed on Joomla 3.10.11 running php 8.0.28 and mysql 5.5.68. I cannot save the module because I get the following error:
Joomla\CMS\Form\Form::validateField() rule `cleartransientnow` missing.

**Comment by bramwaas** [comment]
Hi staffiery,

I made the module for Joomla 4.0 and later.
The structure of the module parts in Joomla 3 is different, so it won't work there. That is also the background of this error.

Since Joomla 3 is already nearing its end of life, I will not make a version for Joomla 3 anymore.

I'm sorry, but you can only use this module if your site has been upgraded to version 4.

**Comment by bramwaas** [comment]
Won't fix isues for joomla 3 and earlier.
