### ISSUE TITLE
Joomla Version 5.2.1

### ISSUE THREAD

**Issue by Grey-Sheep** [bramwaas/joomla_mod_simple_ical_block#29]
Hi,

I'm not sure if this is an issue, or a configuration error on my part.

Using simple iCal Block on Joomla 5.2.1 the modules does not appear to display any text.  I notice it has been tested to 5.0.3

A simple iwrapper module to the calendar does display fine, and the calendar is in use elsewhere.

I have no example entries when using the #example entry.

I have tried both the system default Template Cassiopeia, and the Purity 4 template.  Neither display any entries
I have tried in different positions and scaling.

The Chrome "F12 debug" and AI suggest that the default height of 24 pixels is an issue, but I can't see any way to alter the height.

Could you please help?

Regards

Jan

**Comment by bramwaas** [comment]
Hi Jan,

Thank you for reporting the issue.
On my own site waasdorpsoekhan.nl  I use it with Joomla 5.2.1. so that is not likely to be the issue.
In the past I have also tested with Cassiopeia but for the last update not so I will Install my test environment with a fresh copy of the newest Joomla 5 and test the module in that environment.

But I think that I need more knowledge of your site to help you.
 If the url is public I would like to see it myself  and look at the source with inspector to see if something invisible is available in the source.
I would als like to know all settings you use with #example, the module position in Cassiopeia and if the module is active on the page or al pages to reproduce your issue as good as possible in my test environment.

If you prefer that you can email me at  bram at my website domain.

Regards Bram

**Comment by bramwaas** [comment]
Hi Jan,

after my first test with a clean Joomla environment I see that the "Categories Filter Operator" for "No filtering" has a default value of "1" while it should be "".  With value "1" no event is selected.


I will change this today.
But maybe you can test with "Categories Filter Operator"  "ANY ..." and the field "Categories Filter List" empty, that should with #example select the events with no category: "Monthly day 29, without category".

Thanks and regards Bram

**Comment by bramwaas** [comment]
Hi Jan,

Thank you for testing my suggestion and sending me the result.

I have now released version 2.5.1 to the extension directory and my update system. So if you update the module to  to 2.5.1 I expect the issue is solved.

Thanks and Regards

Bram
